# Site settings
title: Onkar Shedge | Blog
description: "My blog, build with Jekyll."
url: "http://onkarshedge.github.io"
author:
  name: "Onkar Shedge"
  email: "shedge31onkar@gmail.com"
  url: "http://onkarshedge.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
# permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
